title:             
email:             
description:       
author:            Mr. Braz
baseurl:           "/"
url:               ""

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate